// 连接关系数据
var connectionDataDefault = [
	{
		source: "node14",
		target: "node16",
		sourceAnchor: "Right",
		targetAnchor: "Left",
		sourceNodeType: "node",
		targetNodeType: "node",
	},
	{
		source: "node11",
		target: "node14",
		sourceAnchor: "Right",
		targetAnchor: "Left",
		sourceNodeType: "node",
		targetNodeType: "node",
	},
	{
		source: "node11",
		target: "node15",
		sourceAnchor: "Top",
		targetAnchor: "Left",
		sourceNodeType: "node",
		targetNodeType: "empty",
	},
	{
		source: "node15",
		target: "node13",
		sourceAnchor: "Right",
		targetAnchor: "Left",
		sourceNodeType: "empty",
		targetNodeType: "node",
	},
	{
		source: "node15",
		target: "node12",
		sourceAnchor: "Top",
		targetAnchor: "Left",
		sourceNodeType: "empty",
		targetNodeType: "node",
	},
	{
		source: "node13",
		target: "node17",
		sourceAnchor: "Right",
		targetAnchor: "Left",
		sourceNodeType: "node",
		targetNodeType: "explain",
	},
	{
		source: "node17",
		target: "node16",
		sourceAnchor: "Right",
		targetAnchor: "Top",
		sourceNodeType: "explain",
		targetNodeType: "node",
	},
	{
		source: "node17",
		target: "node1686277149257",
		sourceAnchor: "Top",
		targetAnchor: "Left",
		sourceNodeType: "explain",
		targetNodeType: "node",
	},
];
// 流程图数据
var flowchartDataDefault = [
	{
		id: "node11",
		top: 240,
		left: 101,
		label: "馏分油",
		type: "node",
	},
	{
		id: "node12",
		top: 40,
		left: 338,
		label: "石脑油",
		type: "node",
	},
	{
		id: "node13",
		top: 131,
		left: 341,
		label: "尾油",
		type: "node",
	},
	{
		id: "node14",
		top: 240,
		left: 339,
		label: "润滑油",
		type: "node",
	},
	{
		id: "node15",
		top: 131,
		left: 211,
		label: "",
		type: "empty",
	},
	{
		id: "node16",
		top: 240,
		left: 601,
		label: "润滑油基础油",
		type: "node",
	},
	{
		id: "node17",
		top: 141,
		left: 521,
		label: "126",
		type: "explain",
	},
	{
		id: "node18",
		top: 173,
		left: 415,
		label: "14",
		type: "remark",
	},
	{
		id: "node19",
		top: 250,
		left: 506,
		label: "14",
		type: "explain",
	},
	{
		id: "node20",
		top: 261,
		left: 184,
		label: "13溶剂脱蜡及精致",
		type: "remark",
	},
	{
		id: "node1686277149257",
		top: 54,
		left: 609,
		label: "加一个",
		type: "node",
	},
];
